default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'team_task_development' %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'team_task_test' %>

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'team_task_production' %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>